---
name: Test MariaDB config on Debian 11-12 and testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  debian_11_bullseye:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: "debian:11"
      mariadb_server: "mariadb-server-10.5"

  debian_12_bookworm:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: "debian:12"
      mariadb_server: "mariadb-server"

  debian_sid_testing:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: "debian:testing"
      mariadb_server: "mariadb-server"

