---
name: Test MariaDB config on Debian 13 and testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  debian_13_trixie:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: debian:13
      mariadb_server: mariadb-server
      mariadb_directory: /var/lib/mysql

  debian_sid_unstable:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: debian:unstable
      mariadb_server: mariadb-server
      mariadb_directory: /var/lib/mariadb
