---
name: Test configuration on system MariaDB

on:
  workflow_call:
    inputs:
      container:
        required: true
        type: string
      mariadb_server:
        required: true
        type: string

jobs:
  test-mariadb:
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/GMT

    steps:
      - uses: actions/checkout@v4
      - name: Link correct timezone to '/etc/localtime'
        run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      - name: Enable automatic restarts from maint scripts
        run : sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d
      - name: Fake /sbin/runlevel to avoid warnings of could not determine current runlevel
        run: echo -e '#!/bin/sh\necho "N 5"' > /sbin/runlevel; chmod +x /sbin/runlevel
      - name: Emit non-zero exit code also on warnings
        run: echo 'APT::Update::Error-Mode "any";' > /etc/apt/apt.conf.d/non-zero-exit-on-warnings
      - name: Run 'apt update'
        run: apt update -qq
      - name: Install package 'curl' 
        run: apt install -y libcurl4 curl
      - name: Copy configs to /etc/mysql
        run: |
             mkdir /etc/mysql
             cp -a etc/my.cnf.d/mariadb-config.general.d /etc/mysql
      - name: Install package '${{ inputs.mariadb_server }}'
        run: apt install -y ${{ inputs.mariadb_server }}
      - name: Add include /etc/mysql/mariadb-config.general.d/ dir to my.cnf
        run: echo "!includedir /etc/mysql/mariadb-config.general.d/" >> /etc/mysql/my.cnf
      - name: Reload MariaDB server
        run: /etc/init.d/mariadb restart
      - name: Check that InnoDB variables are applied
        run: cat test/innodb-variables.sql | mariadb
      - name: Check that MariaDB system variables are applied
        run: cat test/system-variables.sql | mariadb
      - name: Check that MariaDB strict variables are applied
        run: cat test/strict-variables.sql | mariadb

