---
name: Test MariaDB config on Ubuntu 22.04-24.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu_24_04_noble_numbat:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: ubuntu:24.04
      mariadb_server: mariadb-server
      mariadb_directory: /var/lib/mysql


  ubuntu_25_10_questing_quokka:
    uses: ./.github/workflows/reusable-mariadb.yml
    with:
      container: ubuntu:25.10
      mariadb_server: mariadb-server
      mariadb_directory: /var/lib/mysql

